pipeline {
    agent any
    stages {
        stage('infra init') {
            steps {
                withAWS(credentials:'aws-credentials') {
                    dir('infra') {
                        sh 'terraform init -reconfigure'
                        sh 'terraform workspace new dev'
                        sh 'terraform workspace select dev'
                        sh 'terraform apply --var-file dev.tfvars -auto-approve'
                    }
                }
            }
        }
    }
}
