pipeline {
    agent { 
        label 'master'
    }
    stages {
        stage('infra init') {
            steps {
                withAWS(credentials:'aws-credentials') {
                    dir('infra') {
                        sh 'terraform init -reconfigure'
                        //sh 'terraform workspace new dev 2> /dev/null'
                        //sh 'terraform workspace select dev'
                        sh 'terraform apply --var-file dev.tfvars -auto-approve'
                    }
                }
            }
        }
        stage('gathering outputs') {
            steps {
                withAWS(credentials:'aws-credentials') {
                    dir('infra') {
                        sh 'terraform state pull'
                        sh 'terraform state list'                        
                        sh 'terraform show aws_instance.ec2a'
                        //sh 'terraform state show aws_instance.ec2b.private_ip'                        
                    }
                }
            }
        }
    }
}
