pipeline {
    agent any
    stages {
        stage('infra init') {
            steps {
                dir('infra') {
                    sh "pwd"
                }
                sh 'terraform init -reconfigure'
                sh 'terraform workspace new dev'
                sh 'terraform workspace select dev'
                sh 'terraform apply --var-file dev.tfvars -auto-approve'
            }
        }
    }
}
